### ISSUE TITLE
api.GetBucketList Error !!! | XMLParserError | Unexpected close tag Line

### ISSUE THREAD

**Issue by hcgvic** [necatiarslan/aws-s3#17]
Hello,

It seems as though my sax package is not parsing correctly when I am trying to access my S3 bucket via the extension. I have confirmed that my credentials are correct and that my sax package is fully updated. Please refer to the images below for the errors

```
api.GetBucketList Error !!!
XMLParserError
Unexpected close tag
Line: 15
Column: 7
Char: >
XMLParserError: Unexpected close tag
Line: 15
Column: 7
Char: >

at error (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\sax\lib\sax.js:667:10)
	at strictFail (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\sax\lib\sax.js:693:7)
	at closeTag (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\sax\lib\sax.js:887:9)
	at SAXParser.write (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\sax\lib\sax.js:1449:13)
	at exports.Parser.Parser.parseString (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\xml2js\lib\parser.js:322:31)
	at Parser.parseString (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\xml2js\lib\parser.js:5:59)
	at NodeXmlParser.parse (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\xml\node_parser.js:31:10)
	at Request.extractData (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\protocol\rest_xml.js:96:23)
	at Request.callListeners (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
	at Request.emit (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
	at Request.emit (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:686:14)
	at Request.transition (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:22:10)
	at AcceptorStateMachine.runTo (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\state_machine.js:14:12)
	at c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\state_machine.js:26:10
	at Request.<anonymous> (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:38:9)
	at Request.<anonymous> (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:688:12)
	at Request.callListeners (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
	at Request.emit (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
	at Request.emit (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:686:14)
	at Request.transition (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:22:10)
	at AcceptorStateMachine.runTo (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\state_machine.js:14:12)
	at c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\state_machine.js:26:10
	at Request.<anonymous> (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:38:9)
	at Request.<anonymous> (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\request.js:688:12)
	at Request.callListeners (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
	at callNextListener (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
	at IncomingMessage.onEnd (c:\Users\vsamuel\.vscode\extensions\necatiarslan.aws-s3-vscode-extension-1.5.0\node_modules\aws-sdk\lib\event_listeners.js:417:13)
	at IncomingMessage.emit (node:events:525:35)
	at IncomingMessage.emit (node:domain:489:12)
	at endReadableNT (node:internal/streams/readable:1359:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by necatiarslan** [comment]
It seems like a Windows-related issue.
At what exact point you are getting this error?
What you were doing?

**Comment by hcgvic** [comment]
Thank you for your quick response.

I was attempting to search a bucket using the `+` button in the menu bar of this extensions left panel
![image](https://github.com/necatiarslan/aws-s3/assets/156102361/53a43018-54ee-41ca-88e7-8895da2352f0)

I have also tried these same steps with the same credentials in an AWS EC2 Linux instance with the same error

**Comment by necatiarslan** [comment]
let me know if this is fixed
